document.addEventListener("DOMContentLoaded", () => {
const lazyload = () => { let lazyImg = document.querySelectorAll("img.lazy"); let observer = new IntersectionObserver((entries, observe) => { entries.forEach((entry) => { if (!entry.isIntersecting) return; entry.target.setAttribute("src", entry.target.getAttribute("data-src")); entry.target.classList.remove("lazy"); observe.unobserve(entry.target); }); }); lazyImg.forEach((entry) => { observer.observe(entry); }); };
let t = 0;window.addEventListener("scroll", () => {if (t == 0) { lazyload(); t = 1; }});setTimeout(() => {if (t == 0) {lazyload();t = 1;}}, 5000);
const _g0e0t = (_after, _type, _query) => { let surl = `/api/a0i1w2a3l4l5p6a7p8e9r0online?t=${_type}&n=${_after}&q=${_query}`; return new Promise((resolve, reject) => { var xhttp = new XMLHttpRequest(); xhttp.onreadystatechange = function () { if (this.readyState === 4) { if (this.status === 200) { resolve(this.responseText); } else { reject(this.statusText); } } }; xhttp.open("GET", surl, true); xhttp.send(); }); };
let loaderGif = document.querySelector(".loader-gif");
let gallery = document.querySelector(".gallery");
let qu = "";
const checkLoad = () => { let loader = document.querySelector(".loader-gif-on-scroll"); let obs_loader = new IntersectionObserver((entries, observe) => { entries.forEach((entry) => { if (!entry.isIntersecting) return; loaderGif.style.display = "block"; const t = entry.target.getAttribute("data-type"); let n = document.querySelectorAll(".gallery-img-object"); n = n[n.length - 1]; const nd = n.getAttribute("data-cid"); if (t != "hpe") { if(qu==""){ qu = n.getAttribute("data-query");} } else { qu = "none";}
_g0e0t(nd, t, qu).then((x) => {loaderGif.style.display = "none"; observe.unobserve(entry.target); if (x) { gallery.insertAdjacentHTML("beforeend", x); lazyload(); checkLoad(); } else { gallery.insertAdjacentHTML( "afterend", '<div style="text-align:center;">No related wallpaper, check out our recent wallpapers.</div>' ); } }).catch((err) => { gallery.insertAdjacentHTML( "afterend", '<div style="text-align:center;">No related wallpaper, check out our recent wallpapers.</div>' ); console.error(err); }); }); }); obs_loader.observe(loader); }; checkLoad(); });
